create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  worker_code text unique not null,
  name text not null,
  department text default '',
  photo_path text not null,
  embedding jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete cascade,
  attendance_date date not null,
  attendance_time time not null,
  photo_path text not null,
  method text not null,
  confidence double precision,
  created_at timestamptz not null default now(),
  unique(worker_id, attendance_date)
);

create index if not exists idx_attendance_date on public.attendance(attendance_date);
create index if not exists idx_attendance_worker on public.attendance(worker_id);

alter table public.workers enable row level security;
alter table public.attendance enable row level security;

-- Private storage buckets for worker registration and attendance photos.
insert into storage.buckets (id, name, public)
values ('worker-photos', 'worker-photos', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('attendance-photos', 'attendance-photos', false)
on conflict (id) do update set public = false;

-- No public table/storage policies are required because FastAPI uses the server-side secret key.
